<?php

/**
 * BaseUserSettings
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property boolean $show_on_all_websites
 * @property sfGuardUser $User
 * 
 * @method integer      getUserId()               Returns the current record's "user_id" value
 * @method boolean      getShowOnAllWebsites()    Returns the current record's "show_on_all_websites" value
 * @method sfGuardUser  getUser()                 Returns the current record's "User" value
 * @method UserSettings setUserId()               Sets the current record's "user_id" value
 * @method UserSettings setShowOnAllWebsites()    Sets the current record's "show_on_all_websites" value
 * @method UserSettings setUser()                 Sets the current record's "User" value
 * 
 * @package    cms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserSettings extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_settings');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('show_on_all_websites', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}