<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Website', 'doctrine');

/**
 * BaseWebsite
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $namespace
 * @property string $url
 * @property boolean $is_secure
 * @property Doctrine_Collection $Projects
 * 
 * @method string              getNamespace() Returns the current record's "namespace" value
 * @method string              getUrl()       Returns the current record's "url" value
 * @method boolean             getIsSecure()  Returns the current record's "is_secure" value
 * @method Doctrine_Collection getProjects()  Returns the current record's "Projects" collection
 * @method Website             setNamespace() Sets the current record's "namespace" value
 * @method Website             setUrl()       Sets the current record's "url" value
 * @method Website             setIsSecure()  Sets the current record's "is_secure" value
 * @method Website             setProjects()  Sets the current record's "Projects" collection
 * 
 * @package    cms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseWebsite extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('website');
        $this->hasColumn('namespace', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('is_secure', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('WebsiteProject as Projects', array(
             'local' => 'id',
             'foreign' => 'website_id'));
    }
}