<?php

/**
 * BaseWebappConfig
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $website_project_id
 * @property string $config
 * @property boolean $is_active
 * @property sfGuardUser $User
 * @property WebsiteProject $WebsiteProject
 * 
 * @method integer        getUserId()             Returns the current record's "user_id" value
 * @method integer        getWebsiteProjectId()   Returns the current record's "website_project_id" value
 * @method string         getConfig()             Returns the current record's "config" value
 * @method boolean        getIsActive()           Returns the current record's "is_active" value
 * @method sfGuardUser    getUser()               Returns the current record's "User" value
 * @method WebsiteProject getWebsiteProject()     Returns the current record's "WebsiteProject" value
 * @method WebappConfig   setUserId()             Sets the current record's "user_id" value
 * @method WebappConfig   setWebsiteProjectId()   Sets the current record's "website_project_id" value
 * @method WebappConfig   setConfig()             Sets the current record's "config" value
 * @method WebappConfig   setIsActive()           Sets the current record's "is_active" value
 * @method WebappConfig   setUser()               Sets the current record's "User" value
 * @method WebappConfig   setWebsiteProject()     Sets the current record's "WebsiteProject" value
 * 
 * @package    cms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseWebappConfig extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('webapp_config');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('website_project_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('config', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('WebsiteProject', array(
             'local' => 'website_project_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}