<?php

/**
 * BaseWebsiteProject2sfGuardUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $website_project_id
 * @property integer $sf_guard_user_id
 * @property WebsiteProject $WebsiteProject
 * @property sfGuardUser $sfGuardUser
 * 
 * @method integer                    getWebsiteProjectId()   Returns the current record's "website_project_id" value
 * @method integer                    getSfGuardUserId()      Returns the current record's "sf_guard_user_id" value
 * @method WebsiteProject             getWebsiteProject()     Returns the current record's "WebsiteProject" value
 * @method sfGuardUser                getSfGuardUser()        Returns the current record's "sfGuardUser" value
 * @method WebsiteProject2sfGuardUser setWebsiteProjectId()   Sets the current record's "website_project_id" value
 * @method WebsiteProject2sfGuardUser setSfGuardUserId()      Sets the current record's "sf_guard_user_id" value
 * @method WebsiteProject2sfGuardUser setWebsiteProject()     Sets the current record's "WebsiteProject" value
 * @method WebsiteProject2sfGuardUser setSfGuardUser()        Sets the current record's "sfGuardUser" value
 * 
 * @package    cms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseWebsiteProject2sfGuardUser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('website_project2sf_guard_user');
        $this->hasColumn('website_project_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('sf_guard_user_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('WebsiteProject', array(
             'local' => 'website_project_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardUser', array(
             'local' => 'sf_guard_user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}