<?php

/**
 * WebsiteProject2sfGuardUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WebsiteProject2sfGuardUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object WebsiteProject2sfGuardUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WebsiteProject2sfGuardUser');
    }
}