<?php

/**
 * WebsiteProjectTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WebsiteProjectTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object WebsiteProjectTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WebsiteProject');
    }
}