DefaultImage:
  connection: doctrine  
  actAs: [ImageBuilder]
  columns:
    name: string(255)
    title: string(255)
    image: {type: string(255), notnull: true} 



    
TextBlock:
  connection: doctrine
  actAs:
    I18n:
      fields: [text]
  columns:
    name: {type: string(255), notnull: true}
    title: {type: string(255)}
    text: string()
    application: string(32)
    module: string(32)
    special_mark: string(32)
    is_visible_for_admin: {type: boolean, default: false}
  indexes:
    section_index:
      fields: [application, module]







  



