Website:
  connection: doctrine
  columns:
    namespace: string(255)
    url: string(255)
    is_secure: {type: boolean, default: true}

WebsiteProject:
  actAs: [Timestampable]
  columns:
    website_id: {type: integer, notnull: true}
    name: string(255)
  relations:
    Website: {foreignAlias: Projects, onDelete: CASCADE}
    Users: {class: sfGuardUser, refClass: WebsiteProject2sfGuardUser, foreignAlias: Projects}

WebsiteProject2sfGuardUser:
  columns:
    website_project_id: {type: integer, primary: true, notnull: true}
    sf_guard_user_id: {type: integer, primary: true, notnull: true}
  relations:
    WebsiteProject: {onDelete: CASCADE}
    sfGuardUser: {onDelete: CASCADE}

DefaultImage:
  connection: doctrine  
  actAs: [ImageBuilder]
  columns:
    name: string(255)
    title: string(255)
    image: {type: string(255), notnull: true} 



    
TextBlock:
  connection: doctrine
  actAs:
    I18n:
      fields: [text]
  columns:
    name: {type: string(255), notnull: true}
    title: {type: string(255)}
    text: string()
    application: string(32)
    module: string(32)
    special_mark: string(32)
    is_visible_for_admin: {type: boolean, default: false}
  indexes:
    section_index:
      fields: [application, module]







  



